/*
testTables_jukeStack
This Script should show important information about the 3 tables and
should test if everything is working as it should.
The script tests if the structure is correct, if we can insert data,
if we can select the data and if we can delete data.


Author: Josua Panzera
Date: 2022-12-13

History:
Version	Date		Who	Changes
1.0  	2022-12-13	JP	created
1.1		2023-01-02	JP	updated test cases
1.2		2023-01-06	JP	added documentation test cases

Copyright ©2022 Josua Panzera
*/
-- checks if the structure is correct
describe TUsers;
describe TLendings;
describe TNFTSongs;
-- some test inserts to check if we can add information
insert into TUsers values ('Steven.Hatch@gmx.com', 'Sir', 'Steven', 'Hatch', 'Q4uCsp}Xaq{|a3kFYb/%1y2ip-wpX?q:67f^\WVW%vS$EPD9#rJK:ZqK}n#zav+y', 'user'); -- in the Real data the password would be hashed
insert into TNFTSongs values('qDzUQ37dfQk7Vek4','Kelly Family', 'Country yards', '0:4:08', '2008'); -- in the real data the NFToken would be generated by a script
insert into TLendings(LenStart, NFToken, UsMail) values(now(), 'qDzUQ37dfQk7Vek4', 'Steven.Hatch@gmx.com');
insert into TUsers values ('Peter.Griffin@outlook.com', 'Sir', 'Peter', 'Griffin', 'F@KERx.JZkF#F^4?2(&[Qs3m%54*w<[m.@M3:=Yt+$K!^^zn&Nd}(CBS?G6Ci/-}','admin');
insert into TNFTSongs values('iPPrbc9ggugNVszb', 'Abba', 'Waterloo', '0:2:46', null);
-- some selects to verify the inserts
select * from TUsers;
select * from TNFTSongs;
select * from TLendings;
select UsFName, UsSName, NFName, LenStart from TUsers natural join TLendings natural join TNFTSongs;
-- check if we can delete the inserts
set sql_safe_updates = 0;
truncate TUsers;
truncate TLendings;
alter table TLendings auto_increment = 100000000; -- Have to set this again because after truncate the auto increment is reseted to 1
truncate TNFTSongs;

-- TEST CASES from the documentation
-- 1
insert into TUsers values ('Francois@bluewin.ch', 'Sir', 'Francois', 'Golat', 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', 'user');
select * from TUsers where UsMail = 'Francois@bluewin.ch';
-- 2
update TUsers set UsPasswd = '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4' where UsMail = 'Francois@bluewin.ch';
select * from TUsers where UsMail = 'Francois@bluewin.ch';
-- 3
insert into TNFTSongs values('NFTIanSpe0891995', 'Ian Kelly', 'Speak your Mind', '00:04:08','2008');
select * from TNFTSongs where NFToken = 'NFTIanSpe0891995';
-- 4
update TNFTSongs set NFYear = '2012';
select * from TNFTSongs where NFToken = 'NFTIanSpe0891995';
-- 5
insert into TLendings(LenStart, NFToken, UsMail) values(now(),'NFTIanSpe0891995','Francois@bluewin.ch');
select * from TLendings where LenId = 100000000;
-- 6
update TLendings set LenEnd = now();
select * from TLendings where LenId = 100000000;
-- 7 
delete from TLendings where LenId = 100000000;
select * from TLendings where LenId = 1000000;
-- 8
delete from TUsers where UsMail = 'Francois@bluewin.ch';
select * from TUsers where UsMail = 'Francois@bluewin.ch';
-- 9
delete from TNFTSongs where NFToken = 'NFTIanSpe0891995';
select * from TNFTSongs where NFToken = 'NFTIanSpe0891995';

insert into TUsers (UsMail, UsSalutation, UsFName, UsSName, UsPasswd, UsRole) values ('a.k@gmail.co','Madam','Akaline','Klein','a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', 'admin');
