/*
testTables_jukeStack
This Script should show important information about the 3 tables and
should test if everything is working as it should.
The script tests if the structure is correct, if we can insert data,
if we can select the data and if we can delete data.


Author: Josua Panzera
Date: 2022-12-13

History:
Version	Date		Who	Changes
1.0  	2022-12-13	JP	created

Copyright ©2022 Josua Panzera
*/
-- checks if the structure is correct
describe TUsers;
describe TLendings;
describe TNFTSongs;
-- some test inserts to check if we can add information
insert into TUsers values ('Steven.Hatch@gmx.com', 'Sir', 'Steven', 'Hatch', 'Q4uCsp}Xaq{|a3kFYb/%1y2ip-wpX?q:67f^\WVW%vS$EPD9#rJK:ZqK}n#zav+y'); -- in the Real data the password would be hashed
insert into TNFTSongs values('qDzUQ37dfQk7Vek4','Ian Kelly', 'Speak your mind', '0:4:08', '2008'); -- in the real data the NFToken would be generated by a script
insert into TLendings(LenStart, NFToken, UsMail) values(now(), 'qDzUQ37dfQk7Vek4', 'Steven.Hatch@gmx.com');
insert into TUsers values ('Peter.Griffin@outlook.com', 'Sir', 'Peter', 'Griffin', 'F@KERx.JZkF#F^4?2(&[Qs3m%54*w<[m.@M3:=Yt+$K!^^zn&Nd}(CBS?G6Ci/-}');
insert into TNFTSongs values('iPPrbc9ggugNVszb', 'Abba', 'Waterloo', '0:2:46', null);
-- some selects to verify the inserts
select * from TUsers;
select * from TNFTSongs;
select * from TLendings;
select UsFName, UsSName, NFName, LenStart from TUsers natural join TLendings natural join TNFTSongs;
-- check if we can delete the inserts
delete from TUsers where UsMail = 'Steven.Hatch@gmx.com' or UsMail = 'peter.griffin@outlook.com';
delete from TNFTSongs where NFToken = 'qDzUQ37dfQk7Vek4' or NFToken = 'iPPrbc9ggugNVszb';
delete from TLendings where LenId = 1000000;

