import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import { CookiesProvider } from "react-cookie"; //needed for cookies in all sites


const root = ReactDOM.createRoot(document.getElementById('root')); //standard react app root (generated by npm create react-app)
root.render(
  <React.StrictMode>
      <CookiesProvider> {/*cookie container -> parsable to all sites*/}
          <App />
      </CookiesProvider>
  </React.StrictMode>
);

